stages:
  - build
  
test:
  stage: build
  environment:
    name: staging
  script:
    - git submodule update --init --remote #if you don't have submodules in your project you can remove this line
    - SET BDS=C:\\Program Files (x86)\\Embarcadero\\Studio\\15.0
    - SET BDSINCLUDE=C:\\Program Files (x86)\\Embarcadero\\Studio\\15.0\\include
    - SET BDSCOMMONDIR=C:\\Users\\Public\\Documents\\Embarcadero\\Studio\\15.0
    - SET FrameworkDir=C:\\Windows\\Microsoft.NET\\Framework\\v3.5
    - SET FrameworkVersion=v3.5
    - SET FrameworkSDKDir=
    - SET PATH=%FrameworkDir%;%FrameworkSDKDir%;C:\\Program Files (x86)\\Embarcadero\\Studio\\15.0\\bin;C:\\Program Files (x86)\\Embarcadero\\Studio\\15.0\\bin64;C:\\Users\\Public\\Documents\\Embarcadero\\InterBase\\redist\\InterBaseXE3\\win32_togo;C:\\Users\\Public\\Documents\\Embarcadero\\InterBase\\redist\\InterBaseXE3\\win64_togo;%PATH%
    - SET LANGDIR=EN
    - SET PLATFORM=
    - SET PlatformSDK=
    - SET CG_BOOST_ROOT=C:\\Program Files (x86)\\Embarcadero\\Studio\\15.0\\include\\boost_1_39
    - SET CG_64_BOOST_ROOT=C:\\Program Files (x86)\\Embarcadero\\Studio\\15.0\\include\\boost_1_50
    - C:\\Windows\\Microsoft.NET\\Framework\\v3.5\\msbuild /target:Build /property:config=Release;UsePackages=false /verbosity:q Project.dproj
  artifacts:
    name: "%CI_PROJECT_NAME%_%CI_BUILD_NAME%_%CI_BUILD_REF_NAME%_%CI_BUILD_ID%"
    paths:
      - bin\Project.exe   
    when: always
    expire_in: 2 week
production:
  type: build
  environment:
    name: production
  script:
    - git submodule update --init --remote
    - SET BDS=C:\\Program Files (x86)\\Embarcadero\\Studio\\15.0
    - SET BDSINCLUDE=C:\\Program Files (x86)\\Embarcadero\\Studio\\15.0\\include
    - SET BDSCOMMONDIR=C:\\Users\\Public\\Documents\\Embarcadero\\Studio\\15.0
    - SET FrameworkDir=C:\\Windows\\Microsoft.NET\\Framework\\v3.5
    - SET FrameworkVersion=v3.5
    - SET FrameworkSDKDir=
    - SET PATH=%FrameworkDir%;%FrameworkSDKDir%;C:\\Program Files (x86)\\Embarcadero\\Studio\\15.0\\bin;C:\\Program Files (x86)\\Embarcadero\\Studio\\15.0\\bin64;C:\\Users\\Public\\Documents\\Embarcadero\\InterBase\\redist\\InterBaseXE3\\win32_togo;C:\\Users\\Public\\Documents\\Embarcadero\\InterBase\\redist\\InterBaseXE3\\win64_togo;%PATH%
    - SET LANGDIR=EN
    - SET PLATFORM=
    - SET PlatformSDK=
    - SET CG_BOOST_ROOT=C:\\Program Files (x86)\\Embarcadero\\Studio\\15.0\\include\\boost_1_39
    - SET CG_64_BOOST_ROOT=C:\\Program Files (x86)\\Embarcadero\\Studio\\15.0\\include\\boost_1_50
    - C:\\Windows\\Microsoft.NET\\Framework\\v3.5\\msbuild /target:Build /property:config=Release;UsePackages=false /verbosity:q Project.dproj
  artifacts:
    name: "%CI_PROJECT_NAME%_%CI_BUILD_NAME%_%CI_BUILD_REF_NAME%_%CI_BUILD_ID%"
    paths:
      - bin\Project.exe
    when: always
    expire_in: 2 week
  only:
  - tags